# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            VLSI Testing
tagline:          'F# |> Love'
description:      'A place to get started for your testing adventures in F#'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Anjan Kumar'
  url:            https://twitter.com/pnsakanjankumar

paginate:         5

# Gems
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
